language: python
os:
  - linux
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
before_install:
 - pip2.7 install virtualenv
 - pip install virtualenv
install: python setup.py develop
script: python setup.py test
